### ISSUE TITLE
no works widthLimit: ResponsiveScreen.limits['lg'],

### ISSUE THREAD

**Issue by zkmark** [rafaelsetragni/flutter_responsive#1]
The example does not work with: 
**widthLimit: ResponsiveScreen.limits['lg'],** 

https://pub.dev/packages/flutter_responsive#grid-usage

widthLimit, was it changed for another property?

```
ResponsiveContainer(

  // Determines the container's limit size
  widthLimit: ResponsiveScreen.limits['lg'],
  margin: EdgeInsets.symmetric(horizontal: 10),
  
  children: <Widget>[
  
    ResponsiveRow(),
    ResponsiveRow(),
    ResponsiveRow(),
    
  ]
)
```

**Comment by rafaelsetragni** [comment]
widthLimit property works limiting the width to 90% of the size of Bootstrap Limits, in case of Container. For Rows and Columns it works in opose way.

This plugin mimics the Bootstrap web behaviour, so:

Container: Gets 90% full width, until screen ultrapasses the limit defined.
Rows and Cols: Is limited to his width fraction until gets lower than limit defined. After that, it becomes 90% full width.

I do not test this plugin for Flutter web. I will test it and reply here my results.

And, more important: You are welcome to change the code and upload it, if you want to contribute. Right now i am the only one working on the project, so the project are missing hands to be improved quickier as needed.

OBS: 90% is the same thing than 100% column width and side padding in 5%.
